#!/usr/bin/env python3
"""Writes contents/ui/emoji.js from github/gemoji's db/emoji.json, the table ntfy's own apps use.

    python3 tools/gen-emoji.py path/to/gemoji/db/emoji.json > contents/ui/emoji.js

gemoji's short aliases come first and always win, so every tag ntfy renders renders the same.
After them come the Unicode names ("magnifying_glass_tilted_left"), which is what senders
tend to guess, and then every name cut short at a word boundary ("magnifying_glass"), taken
by the first emoji that has it, unless it ends on a word like "in".
"""
import json
import re
import sys

rows = json.load(open(sys.argv[1], encoding="utf-8"))
table = {}
for r in rows:
    for a in r["aliases"]:
        table.setdefault(a, r["emoji"])
names = [(re.sub(r"[^a-z0-9]+", "_", r["description"].lower()).strip("_"), r["emoji"]) for r in rows]
for name, emoji in names:
    table.setdefault(name, emoji)
# "woman_in" or "face_with" would name nothing a sender means
dangling = {"a", "an", "and", "at", "for", "from", "in", "of", "on", "the", "with", "without"}
for name, emoji in names:
    words = name.split("_")
    for n in range(len(words) - 1, 1, -1):
        if words[n - 1] not in dangling:
            table.setdefault("_".join(words[:n]), emoji)

print(".pragma library")
print()
print("// ntfy tag -> emoji, from github/gemoji db/emoji.json (MIT). See ../THIRD_PARTY_NOTICES.md.")
print("// Generated by tools/gen-emoji.py")
print("var byTag = " + json.dumps(table, ensure_ascii=False, indent=2))
